#!/usr/bin/env python3
import os
import shutil
import sys
from pathlib import Path

SPACEFOX_ROOT = Path(__file__).resolve().parent.parent
COSMOS_ROOT = Path(os.environ.get("COSMOS_ROOT", Path.home() / "os" / "cosmos"))
sys.path.insert(0, str(COSMOS_ROOT / "userland"))

from backend import theme  # noqa: E402

OUT_DIR = SPACEFOX_ROOT / "theme" / "generated"
FONTS_SRC = COSMOS_ROOT / "userland" / "fonts"


def rgb(c):
    return f"rgb({c[0]}, {c[1]}, {c[2]})"


def rgba(c):
    if len(c) == 4:
        return f"rgba({c[0]}, {c[1]}, {c[2]}, {c[3] / 255:.3f})"
    return rgb(c)


def main():
    fonts_out = OUT_DIR / "fonts"
    fonts_out.mkdir(parents=True, exist_ok=True)
    for weight_file in ("regular.ttf", "light.ttf", "bold.ttf"):
        shutil.copy(FONTS_SRC / weight_file, fonts_out / weight_file)

    font_face = """
@font-face { font-family: "CosmOSFont"; src: url("fonts/regular.ttf"); font-weight: 400; }
@font-face { font-family: "CosmOSFont"; src: url("fonts/light.ttf"); font-weight: 300; }
@font-face { font-family: "CosmOSFont"; src: url("fonts/bold.ttf"); font-weight: 700; }
"""

    palette = f"""
:root {{
  --cosmos-bg: {rgb(theme.BG)};
  --cosmos-text: {rgb(theme.TEXT)};
  --cosmos-fg: {rgb(theme.FG)};
  --cosmos-fg-bright: {rgb(theme.FG_BRIGHT)};
  --cosmos-fg-dim: {rgb(theme.FG_DIM)};
  --cosmos-accent: {rgb(theme.ACCENT)};
  --cosmos-select-bg: {rgb(theme.SELECT_BG)};
  --cosmos-select-fg: {rgb(theme.SELECT_FG)};
  --cosmos-panel: {rgba(theme.PANEL_FILL)};
  --cosmos-status: {rgb(theme.STATUS_FG)};
}}
"""

    user_chrome = f"""/* Auto-generated by theme/generate_userchrome.py -- do not hand-edit. */
{font_face}
{palette}
* {{
  font-family: "CosmOSFont", sans-serif !important;
}}

#navigator-toolbox,
#TabsToolbar,
#nav-bar,
#PersonalToolbar {{
  background: var(--cosmos-bg) !important;
  color: var(--cosmos-text) !important;
  border-color: var(--cosmos-fg-dim) !important;
}}

.tab-background {{
  background: var(--cosmos-bg) !important;
}}

.tab-background[selected] {{
  background: var(--cosmos-panel) !important;
  box-shadow: inset 0 -2px var(--cosmos-accent) !important;
}}

.tab-label,
#urlbar,
#urlbar-input {{
  color: var(--cosmos-text) !important;
}}

#urlbar {{
  background: var(--cosmos-panel) !important;
  border-color: var(--cosmos-fg-dim) !important;
}}

#urlbar[focused="true"] {{
  border-color: var(--cosmos-accent) !important;
}}

toolbarbutton:hover,
.tab-background:hover {{
  background: var(--cosmos-fg-dim) !important;
}}

::selection {{
  background: var(--cosmos-select-bg) !important;
  color: var(--cosmos-select-fg) !important;
}}
"""

    user_content = f"""/* Auto-generated by theme/generate_userchrome.py -- do not hand-edit. */
{font_face}
@-moz-document url-prefix("about:") {{
  :root {{
    background-color: {rgb(theme.BG)} !important;
    color: {rgb(theme.TEXT)} !important;
  }}
  * {{
    font-family: "CosmOSFont", sans-serif !important;
  }}
  a {{ color: {rgb(theme.ACCENT)} !important; }}
}}
"""

    (OUT_DIR / "userChrome.css").write_text(user_chrome)
    (OUT_DIR / "userContent.css").write_text(user_content)
    print(f"Wrote {OUT_DIR}/userChrome.css, userContent.css, fonts/")


if __name__ == "__main__":
    main()
